<?xml version="1.0"?>
<!--
  ULTRABOT AGV - URDF Robot Description
  Differential drive AGV with safety-critical frame definitions
  
  TF Tree:
    base_footprint (ground projection)
      └─ base_link (robot center)
          ├─ laser_frame (LiDAR sensor - front center)
          ├─ imu_link (IMU sensor - robot center)
          ├─ left_wheel_link (left drive wheel)
          └─ right_wheel_link (right drive wheel)
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ultrabot">

  <!-- ===================================================================== -->
  <!-- PARAMETERS (from robot_config.yaml) -->
  <!-- ===================================================================== -->
  <xacro:property name="wheel_separation" value="0.5" />   <!-- distance_wheels -->
  <xacro:property name="wheel_diameter" value="0.17" />     <!-- wheel_diameter -->
  <xacro:property name="wheel_radius" value="${wheel_diameter / 2.0}" />
  <xacro:property name="wheel_width" value="0.05" />
  
  <xacro:property name="base_length" value="0.6" />
  <xacro:property name="base_width" value="0.5" />
  <xacro:property name="base_height" value="0.3" />
  
  <!-- Sensor mounting positions -->
  <xacro:property name="lidar_front_x" value="0.25" />      <!-- Front 2D LiDAR -->
  <xacro:property name="lidar_front_z" value="0.20" />
  <xacro:property name="lidar_rear_x" value="-0.25" />      <!-- Rear 2D LiDAR -->
  <xacro:property name="lidar_rear_z" value="0.20" />
  <xacro:property name="lidar_3d_x" value="0.0" />          <!-- 3D LiDAR (Ouster) top center -->
  <xacro:property name="lidar_3d_z" value="0.35" />
  <xacro:property name="realsense_front_left_x" value="0.22" />   <!-- Front-left RealSense D455 -->
  <xacro:property name="realsense_front_left_y" value="0.15" />
  <xacro:property name="realsense_front_left_z" value="0.15" />
  <xacro:property name="realsense_front_right_x" value="0.22" />  <!-- Front-right RealSense D455 -->
  <xacro:property name="realsense_front_right_y" value="-0.15" />
  <xacro:property name="realsense_front_right_z" value="0.15" />

  <!-- ===================================================================== -->
  <!-- MATERIALS (Visual Colors for RViz) -->
  <!-- ===================================================================== -->
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <!-- ===================================================================== -->
  <!-- BASE_FOOTPRINT (Ground Projection - Nav2 Planning Reference) -->
  <!-- ===================================================================== -->
  <!-- This is the 2D projection of the robot on the ground plane.
       Nav2 uses this as the reference frame for costmaps and planning. -->
  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.001"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <!-- ===================================================================== -->
  <!-- BASE_LINK (Robot Center - Origin of Robot Coordinate System) -->
  <!-- ===================================================================== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="50.0"/>  <!-- 50 kg AGV -->
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" 
               iyy="1.0" iyz="0.0" 
               izz="1.0"/>
    </inertial>
  </link>

  <!-- Joint: base_footprint → base_link (fixed, Z-offset = wheel_radius) -->
  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- LEFT WHEEL LINK -->
  <!-- ===================================================================== -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" 
               iyy="0.01" iyz="0.0" 
               izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint: base_link → left_wheel_link (continuous rotation) -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>  <!-- Rotation axis (Y-axis for side wheels) -->
  </joint>

  <!-- ===================================================================== -->
  <!-- RIGHT WHEEL LINK -->
  <!-- ===================================================================== -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" 
               iyy="0.01" iyz="0.0" 
               izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint: base_link → right_wheel_link (continuous rotation) -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${-wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- FRONT 2D LIDAR (e.g., SICK TiM571, Hokuyo UST-10LX) -->
  <!-- ===================================================================== -->
  <link name="scan_front_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
               iyy="0.001" iyz="0.0" 
               izz="0.001"/>
    </inertial>
  </link>

  <joint name="scan_front_joint" type="fixed">
    <parent link="base_link"/>
    <child link="scan_front_link"/>
    <origin xyz="${lidar_front_x} 0 ${lidar_front_z}" rpy="0 0 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- REAR 2D LIDAR (Rear Coverage for Obstacle Detection) -->
  <!-- ===================================================================== -->
  <link name="scan_rear_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
               iyy="0.001" iyz="0.0" 
               izz="0.001"/>
    </inertial>
  </link>

  <joint name="scan_rear_joint" type="fixed">
    <parent link="base_link"/>
    <child link="scan_rear_link"/>
    <origin xyz="${lidar_rear_x} 0 ${lidar_rear_z}" rpy="0 0 ${pi}"/>  <!-- 180° rotation -->
  </joint>

  <!-- ===================================================================== -->
  <!-- 3D LIDAR (Ouster OS1-64/OS1-128 - PointCloud2) -->
  <!-- ===================================================================== -->
  <link name="ouster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.06" length="0.08"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.06" length="0.08"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.8"/>
      <inertia ixx="0.002" ixy="0.0" ixz="0.0" 
               iyy="0.002" iyz="0.0" 
               izz="0.002"/>
    </inertial>
  </link>

  <joint name="ouster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ouster_link"/>
    <origin xyz="${lidar_3d_x} 0 ${lidar_3d_z}" rpy="0 0 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- REALSENSE D455 - FRONT LEFT -->
  <!-- ===================================================================== -->
  <link name="camera_front_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.026 0.090 0.025"/>  <!-- D455 dimensions -->
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.026 0.090 0.025"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.12"/>  <!-- ~120g -->
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
               iyy="0.0001" iyz="0.0" 
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_front_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_front_left_link"/>
    <origin xyz="${realsense_front_left_x} ${realsense_front_left_y} ${realsense_front_left_z}" rpy="0 0 0"/>
  </joint>

  <!-- Optical frame (RealSense convention: Z forward, Y down) -->
  <link name="camera_front_left_depth_optical_frame"/>
  
  <joint name="camera_front_left_depth_optical_joint" type="fixed">
    <parent link="camera_front_left_link"/>
    <child link="camera_front_left_depth_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>  <!-- Rotate to optical frame -->
  </joint>

  <!-- ===================================================================== -->
  <!-- REALSENSE D455 - FRONT RIGHT -->
  <!-- ===================================================================== -->
  <link name="camera_front_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.026 0.090 0.025"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.026 0.090 0.025"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.12"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
               iyy="0.0001" iyz="0.0" 
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_front_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_front_right_link"/>
    <origin xyz="${realsense_front_right_x} ${realsense_front_right_y} ${realsense_front_right_z}" rpy="0 0 0"/>
  </joint>

  <!-- Optical frame -->
  <link name="camera_front_right_depth_optical_frame"/>
  
  <joint name="camera_front_right_depth_optical_joint" type="fixed">
    <parent link="camera_front_right_link"/>
    <child link="camera_front_right_depth_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>
  
  <!-- Legacy compatibility: keep laser_frame pointing to front 2D LiDAR -->
  <link name="laser_frame"/>
  <joint name="laser_frame_joint" type="fixed">
    <parent link="scan_front_link"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- IMU LINK (Inertial Measurement Unit - Robot Center) -->
  <!-- ===================================================================== -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
               iyy="0.0001" iyz="0.0" 
               izz="0.0001"/>
    </inertial>
  </link>

  <!-- Joint: base_link → imu_link (fixed, center position) -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
