<?xml version="1.0"?>
<!--
  ULTRABOT AGV - URDF Robot Description
  Differential drive AGV with safety-critical frame definitions
  
  TF Tree:
    base_footprint (ground projection)
      └─ base_link (robot center)
          ├─ laser_frame (LiDAR sensor - front center)
          ├─ imu_link (IMU sensor - robot center)
          ├─ left_wheel_link (left drive wheel)
          └─ right_wheel_link (right drive wheel)
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ultrabot">

  <!-- ===================================================================== -->
  <!-- PARAMETERS (from robot_config.yaml) -->
  <!-- ===================================================================== -->
  <xacro:property name="wheel_separation" value="0.5" />   <!-- distance_wheels -->
  <xacro:property name="wheel_diameter" value="0.17" />     <!-- wheel_diameter -->
  <xacro:property name="wheel_radius" value="${wheel_diameter / 2.0}" />
  <xacro:property name="wheel_width" value="0.05" />
  
  <xacro:property name="base_length" value="0.6" />
  <xacro:property name="base_width" value="0.5" />
  <xacro:property name="base_height" value="0.3" />
  
  <xacro:property name="laser_x" value="0.25" />            <!-- LiDAR front offset -->
  <xacro:property name="laser_z" value="0.20" />            <!-- LiDAR height -->

  <!-- ===================================================================== -->
  <!-- MATERIALS (Visual Colors for RViz) -->
  <!-- ===================================================================== -->
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <!-- ===================================================================== -->
  <!-- BASE_FOOTPRINT (Ground Projection - Nav2 Planning Reference) -->
  <!-- ===================================================================== -->
  <!-- This is the 2D projection of the robot on the ground plane.
       Nav2 uses this as the reference frame for costmaps and planning. -->
  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.001"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <!-- ===================================================================== -->
  <!-- BASE_LINK (Robot Center - Origin of Robot Coordinate System) -->
  <!-- ===================================================================== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="50.0"/>  <!-- 50 kg AGV -->
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" 
               iyy="1.0" iyz="0.0" 
               izz="1.0"/>
    </inertial>
  </link>

  <!-- Joint: base_footprint → base_link (fixed, Z-offset = wheel_radius) -->
  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- LEFT WHEEL LINK -->
  <!-- ===================================================================== -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" 
               iyy="0.01" iyz="0.0" 
               izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint: base_link → left_wheel_link (continuous rotation) -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>  <!-- Rotation axis (Y-axis for side wheels) -->
  </joint>

  <!-- ===================================================================== -->
  <!-- RIGHT WHEEL LINK -->
  <!-- ===================================================================== -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" 
               iyy="0.01" iyz="0.0" 
               izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint: base_link → right_wheel_link (continuous rotation) -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${-wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- LASER FRAME (LiDAR Sensor - Front Center) -->
  <!-- ===================================================================== -->
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
               iyy="0.001" iyz="0.0" 
               izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint: base_link → laser_frame (fixed, front center position) -->
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="${laser_x} 0 ${laser_z}" rpy="0 0 0"/>
  </joint>

  <!-- ===================================================================== -->
  <!-- IMU LINK (Inertial Measurement Unit - Robot Center) -->
  <!-- ===================================================================== -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
               iyy="0.0001" iyz="0.0" 
               izz="0.0001"/>
    </inertial>
  </link>

  <!-- Joint: base_link → imu_link (fixed, center position) -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
